version: 2.1
  

            

jobs:
  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout 
      - run:
          name: Install 1
          command: |
            apk add --update ansible
            pip3 install awscli
            apk update 
            apk upgrade
      - run:
          name: Install 2
          command: |
            apk add curl
            apk add bash
            curl -sL https://rpm.nodesource.com/setup_10.x |  bash -
      - run:
          name: Install 3
          command: |
            apk install -y nodejs
            apk install -y tar gzip
      

 

 
workflows:
  default:
    jobs:
      - deploy-backend:
      
     
